"""Generates blobatar/unicodedata.lua from Python's unicodedata.

Three tables, all encoded as strings and parsed lazily at runtime so an
ASCII-only application never pays for them:

  lower   run-length simple lowercase, as start:count:stride:delta
  lowerx  the mappings runs cannot express, as cp:cp[,cp...]
  ccc     run-length canonical combining class, as start:count:value
  decomp  one-level canonical decomposition, as cp:a[:b]
  comp    the primary composites, as a:b:cp

All numbers are lowercase hex. Composition exclusions are not read from
CompositionExclusions.txt; they are discovered by asking NFC whether a pair
actually recomposes, which is the same question and needs no second file.
"""
import json
import os
import subprocess
import unicodedata as ud

MAX = 0x110000
h = lambda v: format(v, "x")


def runs(pairs):
    """(cp, delta) sorted -> [(start, count, stride, delta)]."""
    out = []
    i = 0
    while i < len(pairs):
        cp, d = pairs[i]
        # Try the longest run at each plausible stride, preferring the one that
        # covers the most codepoints. Stride 1 is the ASCII/Cyrillic case,
        # stride 2 the odd/even pairing all through Latin Extended.
        best = (1, 1)
        for stride in (1, 2):
            n = 1
            while True:
                nxt = (cp + n * stride, d)
                j = i + n
                if j < len(pairs) and pairs[j] == nxt:
                    n += 1
                else:
                    break
            if n > best[1]:
                best = (stride, n)
        stride, n = best
        out.append((cp, n, stride, d))
        i += n
    return out


# The case tables come from the JavaScript engine rather than from here, so a
# case pair added after Python's Unicode version still lowercases the way the
# original library does. See tools/gen_case.mjs.
if not os.path.exists("/tmp/case_tables.json"):
    subprocess.check_call(["node", "tools/gen_case.mjs"])
case = json.load(open("/tmp/case_tables.json"))

ccc = []
for cp in range(MAX):
    v = ud.combining(chr(cp))
    if v:
        ccc.append((cp, v))

decomp = []
for cp in range(MAX):
    d = ud.decomposition(chr(cp))
    if d and not d.startswith("<"):
        decomp.append((cp, [int(x, 16) for x in d.split()]))

comp = []
for cp, parts in decomp:
    if len(parts) != 2:
        continue
    a, b = parts
    # A pair recomposes only if it is not excluded and `a` is a starter.
    if ud.combining(chr(a)) != 0:
        continue
    if ud.normalize("NFC", chr(a) + chr(b)) == chr(cp):
        comp.append((a, b, cp))

ccc_runs = runs([(cp, v) for cp, v in ccc])

parts = []
parts.append('-- Generated by tools/gen_unicode.py from Unicode %s. Do not edit.\n' % ud.unidata_version)
parts.append("return {\n")
parts.append('  version = "%s",\n' % ud.unidata_version)
parts.append('  lower = "%s",\n' % case["lower"])
parts.append('  lowerx = "%s",\n' % case["lowerx"])
parts.append('  cased = "%s",\n' % case["cased"])
parts.append('  ignorable = "%s",\n' % case["ignorable"])
parts.append('  ccc = "%s",\n' % " ".join(
    "%s:%s:%s" % (h(s), h(n), h(d)) for s, n, st, d in ccc_runs if st == 1))
# Any ccc run the stride-1 form cannot express falls back to singletons.
stride2 = [(s, n, st, d) for s, n, st, d in ccc_runs if st != 1]
extra = []
for s, n, st, d in stride2:
    for k in range(n):
        extra.append((s + k * st, d))
if extra:
    parts[-1] = parts[-1][:-3] + " " + " ".join(
        "%s:1:%s" % (h(cp), h(v)) for cp, v in extra) + '",\n'
parts.append('  decomp = "%s",\n' % " ".join(
    "%s:%s" % (h(cp), ":".join(h(x) for x in xs)) for cp, xs in decomp))
parts.append('  comp = "%s",\n' % " ".join(
    "%s:%s:%s" % (h(a), h(b), h(cp)) for a, b, cp in comp))
parts.append("}\n")

open("blobatar/unicodedata.lua", "w").write("".join(parts))
print("ccc runs", len(ccc_runs), "decomp", len(decomp), "comp", len(comp))
